title: Sable Landingham # your name (or website title) here
logo: "/images/4eff8554-5a1f-4de2-8966-04dbadf277fd.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  What's up! My name is Sable Landingham and this is my Programming Portfolio. 
  <br><br>
  I have worked on my interesting projects this semester, so please don't be afraid to browse. 
  <br><br>
  <a href="https://www.linkedin.com/in/sablelandingham/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
